const { db } = require('../config/firebase');

const createBooking = async (req, res) => {
  try {
    const { serviceId, subServiceId, address, scheduledDate, scheduledTime, totalAmount } = req.body;
    const userId = req.user.uid;

    const bookingRef = db.collection('bookings').doc();
    const newBooking = {
      id: bookingRef.id,
      userId,
      serviceId,
      subServiceId,
      address,
      scheduledDate,
      scheduledTime,
      totalAmount,
      status: 'PENDING',
      vendorId: null,
      createdAt: new Date(),
    };

    await bookingRef.set(newBooking);

    // Seed timeline
    await db.collection('booking_timeline').add({
      bookingId: bookingRef.id,
      status: 'PENDING',
      description: 'Booking successfully generated by customer. Awaiting assignment.',
      timestamp: new Date()
    });

    return res.status(201).json({
      success: true,
      message: 'Booking created successfully',
      booking: newBooking
    });
  } catch (error) {
    return res.status(500).json({ success: false, message: 'Booking Creation Failed', error: error.message });
  }
};

const getBookingById = async (req, res) => {
  try {
    const { id } = req.params;
    const bookingSnap = await db.collection('bookings').doc(id).get();

    if (!bookingSnap.exists) {
      return res.status(404).json({ success: false, message: 'Booking not found' });
    }

    return res.status(200).json({ success: true, booking: bookingSnap.data() });
  } catch (error) {
    return res.status(500).json({ success: false, message: 'Query Failed', error: error.message });
  }
};

const updateBookingStatus = async (req, res) => {
  try {
    const { id } = req.params;
    const { status, remarks } = req.body;

    const bookingRef = db.collection('bookings').doc(id);
    const doc = await bookingRef.get();
    if (!doc.exists) {
      return res.status(404).json({ success: false, message: 'Booking not found' });
    }

    await bookingRef.update({ status, lastUpdated: new Date() });

    await db.collection('booking_timeline').add({
      bookingId: id,
      status,
      description: remarks || `Booking status updated to ${status}.`,
      timestamp: new Date()
    });

    return res.status(200).json({ success: true, message: `Status updated to ${status}` });
  } catch (error) {
    return res.status(500).json({ success: false, message: 'Update failed', error: error.message });
  }
};

const getTimeline = async (req, res) => {
  try {
    const { id } = req.params;
    const timelineSnap = await db.collection('booking_timeline')
      .where('bookingId', 'isEqualTo', id)
      .get();

    const timeline = timelineSnap.docs.map(doc => doc.data());
    return res.status(200).json({ success: true, timeline });
  } catch (error) {
    return res.status(500).json({ success: false, message: 'Timeline lookup failed', error: error.message });
  }
};

module.exports = {
  createBooking,
  getBookingById,
  updateBookingStatus,
  getTimeline
};
